export const manufacturers = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const yearsOfProduction = [
  { title: "Year", value: "" },
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
];

export const fuels = [
  {
    title: "Fuel",
    value: "",
  },
  {
    title: "Gas",
    value: "Gas",
  },
  {
    title: "Electricity",
    value: "Electricity",
  },
];

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];

export const allData = [
  {
    title: "2025 HR-V",
    img: "/cars/car-1-2.avif",
    img2: "/cars/car-1-1.avif",
    img3: "/cars/car-1-3.png",
    perday: 35,
    transmition: "automatic",
    mpg: 25,
    drivetrain: "FWD",
  },
  {
    title: "2025 CR-V",
    img: "/cars/car-2-1.jpg",
    img2: "/cars/car-2-2.avif",
    img3: "/cars/car-2-3.avif",
    perday: 47,
    transmition: "manual",
    mpg: 17,
    drivetrain: "AWD",
  },
  {
    title: "2025 Pilot",
    img: "/cars/car-3-1.avif",
    img2: "/cars/car-3-2.avif",
    img3: "/cars/car-3-3.avif",
    perday: 38,
    transmition: "automatic",
    mpg: 19,
    drivetrain: "AWD",
  },
  {
    title: "2025 Speed",
    img: "/cars/car-4-1.jpg",
    img2: "/cars/car-4-2.jpg",
    img3: "/cars/car-4-3.jpg",
    perday: 26,
    transmition: "automatic",
    mpg: 17,
    drivetrain: "FWD",
  },
  {
    title: "2025 Civic Sedan",
    img: "/cars/car-5-1.webp",
    img2: "/cars/car-5-2.avif",
    img3: "/cars/car-5-3.avif",
    perday: 24,
    transmition: "automatic",
    mpg: 17,
    drivetrain: "FWD",
  },
  {
    title: "2024 Civic Type R",
    img: "/cars/car-6-1.avif",
    img2: "/cars/car-6-2.avif",
    img3: "/cars/car-6-3.avif",
    perday: 29,
    transmition: "automatic",
    mpg: 19,
    drivetrain: "AWD",
  },
];
